name: Run rspec, rubocop

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: lint
        run : docker-compose run web rubocop

      - name: test
        run : docker-compose run web rake test
