name: Run rspec, rubocop

on:
  push:
  pull_request:

jobs:
  rubocop:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run rubocop
        run: |
          docker-compose build
          docker-compose up -d
          id=`docker ps | grep "tutorial-web" | awk '{print $1}'`
          docker exec -it ${id} "bundle exec rubocop"
