name: Run rspec, rubocop

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run rubocop
        uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
      # - name: Run RSpec
      #   run: docker-compose run --rm tutorial bundle exec rspec
